name: Build for Windows

on:
  push:
    branches: [ master ]
  workflow_dispatch:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Compiler version
      run: g++ --version
    - name: make
      run: make
    - name: Make output
      run: | 
        mkdir output
        copy .github\bin\*.dll output
        copy main.exe output
    - name: Upload executable
      uses: actions/upload-artifact@v2
      with:
       name: Main executable 
       path: output
